leftnav:
- identifier: 679aaf2c-fc22-4315-a336-52cb3d443ce7
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 2ca6cecf-6bcb-40c1-8bb8-2d4d41311272
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: a0b11dfa-cb8e-41f4-8ff7-d699e9429a57
  name: Readings
  pageRef: /pages/readings
  weight: 30
